#!/system/bin/sh

echo 'Current Scaling:' `cat /proc/cpuinfo | grep BogoMIPS | awk '{print $3}'`
echo 'Current Governor:' `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
echo 'Minimum Frequency:' `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`
echo 'Maximum Frequency:' `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`
