#!/system/bin/sh

mount -o remount,rw -t yaffs2 /dev/block/mtdblock4 /system
mv /system/xbin/hostsshow /system/etc/hosts
cp /system/etc/hosts /system/xbin
mv /system/xbin/hosts /system/xbin/hostsshow
mount -o remount,ro -t yaffs2 /dev/block/mtdblock4 /system
echo Ads Unblocked